package Main.Exceptions;

public class UserNotFound extends RuntimeException{
    public UserNotFound(){super("User Not Found");}
}
